CREATE DATABASE CartagoAgencyDb;
GO
USE CartagoAgencyDb;
GO

CREATE TABLE Users (
    Id INT IDENTITY PRIMARY KEY,
    FullName NVARCHAR(150) NOT NULL,
    Email NVARCHAR(150) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    Role NVARCHAR(50) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Players (
    Id INT IDENTITY PRIMARY KEY,
    FullName NVARCHAR(150) NOT NULL,
    Slug NVARCHAR(150) NOT NULL UNIQUE,
    DateOfBirth DATE NOT NULL,
    Nationality NVARCHAR(100) NOT NULL,
    Height INT NOT NULL,
    Weight INT NOT NULL,
    Position NVARCHAR(100) NOT NULL,
    StrongFoot NVARCHAR(50) NOT NULL,
    CurrentClub NVARCHAR(150) NOT NULL,
    ContractStatus NVARCHAR(150) NOT NULL,
    MatchesPlayed INT NOT NULL,
    Goals INT NOT NULL,
    Assists INT NOT NULL,
    MinutesPlayed INT NOT NULL,
    VideoUrl NVARCHAR(400) NULL,
    TechnicalReportUrl NVARCHAR(400) NULL,
    PhotoUrl NVARCHAR(300) NOT NULL,
    IsFeatured BIT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE TeamMembers (
    Id INT IDENTITY PRIMARY KEY,
    FullName NVARCHAR(150) NOT NULL,
    Role NVARCHAR(150) NOT NULL,
    Bio NVARCHAR(MAX) NOT NULL,
    Email NVARCHAR(150) NOT NULL,
    Phone NVARCHAR(50) NOT NULL,
    PhotoUrl NVARCHAR(300) NOT NULL,
    DisplayOrder INT NOT NULL DEFAULT 1,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE AgencyServices (
    Id INT IDENTITY PRIMARY KEY,
    Title NVARCHAR(150) NOT NULL,
    Category NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    Icon NVARCHAR(100) NOT NULL,
    DisplayOrder INT NOT NULL DEFAULT 1,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE ContactMessages (
    Id INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(150) NOT NULL,
    Email NVARCHAR(150) NOT NULL,
    Subject NVARCHAR(200) NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Unread',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE ClubRequests (
    Id INT IDENTITY PRIMARY KEY,
    ClubName NVARCHAR(150) NOT NULL,
    Country NVARCHAR(100) NOT NULL,
    RecruitmentManager NVARCHAR(150) NOT NULL,
    Email NVARCHAR(150) NOT NULL,
    PhoneNumber NVARCHAR(50) NOT NULL,
    TargetProfile NVARCHAR(200) NOT NULL,
    EstimatedBudget NVARCHAR(120) NOT NULL,
    ContractDuration NVARCHAR(120) NOT NULL,
    AdditionalDetails NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'New',
    AdminNote NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE PlayerApplications (
    Id INT IDENTITY PRIMARY KEY,
    FullName NVARCHAR(150) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Nationality NVARCHAR(100) NOT NULL,
    Position NVARCHAR(100) NOT NULL,
    StrongFoot NVARCHAR(50) NOT NULL,
    Height INT NOT NULL,
    Weight INT NOT NULL,
    CurrentClub NVARCHAR(150) NOT NULL,
    ContractSituation NVARCHAR(200) NOT NULL,
    VideoLink NVARCHAR(400) NOT NULL,
    PhoneNumber NVARCHAR(50) NOT NULL,
    Email NVARCHAR(150) NOT NULL,
    AdditionalNotes NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'New',
    AdminNote NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE SiteSettings (
    Id INT IDENTITY PRIMARY KEY,
    [Key] NVARCHAR(100) NOT NULL UNIQUE,
    Value NVARCHAR(MAX) NOT NULL
);
